modules_dir = "target/wasm32-wasi/release/"
total_memory_limit = "Infinity"

[[module]]
    name = "curl-effector"
    logger_enabled = true
        [module.mapped_dirs]
        mp = "/tmp"
        [module.mounted_binaries]
        curl = "/usr/bin/curl"
